import NavBar from "./components/navbar"
import '../app/globals.css'
import { Bellefair } from '@next/font/google';

const bellefair = Bellefair({
  subsets: ['latin'],
  weight: "400"
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bellefair.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
